#!/bin/sh

ACCS_FILE="${SYNOPKG_PKGDEST}/db/accs.db"
TEMP_DIR="${SYNOPKG_PKGDEST}/../../@tmp"

MV="/bin/mv -f"
RM="/bin/rm -r"
MKDIR="/bin/mkdir -p"
SED="/bin/sed -i -e"

preinst ()
{
exit 0
}

postinst ()
{
    if [ "${wizard_enable_aut}" == "false" ]; then
       ${RM} ${ACCS_FILE}
    else
       ${SED} "s|@user@|${wizard_username:=admin}|g" ${ACCS_FILE}
       ${SED} "s|@password@|${wizard_password:=admin}|g" ${ACCS_FILE}
    fi
exit 0
}

preuninst ()
{
exit 0
}

postuninst ()
{
exit 0
}

preupgrade ()
{
    if [ "${wizard_update_data}" == "false" ]; then
        $RM ${TEMP_DIR}/${SYNOPKG_PKGNAME}
	$MKDIR ${TEMP_DIR}/${SYNOPKG_PKGNAME}
	$MV ${SYNOPKG_PKGDEST}/db ${TEMP_DIR}/${SYNOPKG_PKGNAME}/
    else
        exit 0
    fi
exit 0
}

postupgrade ()
{
    if [ "${wizard_update_data}" == "false" ]; then
        $RM ${SYNOPKG_PKGDEST}/db
        $MV ${TEMP_DIR}/${SYNOPKG_PKGNAME}/db ${SYNOPKG_PKGDEST}/db/
        $RM ${TEMP_DIR}/${SYNOPKG_PKGNAME}
        else
        $RM ${ACCS_FILE}
    fi
exit 0
}
