#!/bin/sh

ACCS="${SYNOPKG_PKGDEST}/db/accs.db"
SSS="/var/packages/${SYNOPKG_PKGNAME}/scripts/start-stop-status"
FWPORTS_FILE="/var/packages/${SYNOPKG_PKGNAME}/conf/${SYNOPKG_PKGNAME}.sc"

preinst ()
{
exit 0
}

postinst ()
{
    if [ "${wizard_enable_aut}" == "false" ]; then
       rm ${ACCS}
    else
       sed -i -e "s|@user@|${wizard_username:=admin}|g" ${ACCS}
       sed -i -e "s|@password@|${wizard_password:=admin}|g" ${ACCS}
    fi

    if [ -r "${FWPORTS_FILE}" ]; then
        servicetool --install-configure-file --package "${FWPORTS_FILE}"
     fi
exit 0
}

preuninst ()
{
        ${SSS} stop > /dev/nul

        if [ "${SYNOPKG_PKG_STATUS}" == "UNINSTALL" ]; then
           if [ -r "${FWPORTS_FILE}" ]; then
               servicetool --remove-configure-file --package "${SYNOPKG_PKGNAME}.sc"
        fi
    fi

exit 0
}

postuninst ()
{
exit 0
}

preupgrade ()
{

    if [ "${wizard_update_data}" == "false" ]; then
        rm -r ${TMP_DIR}/${SYNOPKG_PKGNAME}
	mkdir -p ${TMP_DIR}/${SYNOPKG_PKGNAME}
	mv -f ${SYNOPKG_PKGDEST}/db ${TMP_DIR}/${SYNOPKG_PKGNAME}/
 fi

exit 0
}

postupgrade ()
{

    if [ "${wizard_update_data}" == "false" ]; then
        rm -r ${SYNOPKG_PKGDEST}/db
        mv -f ${TMP_DIR}/${SYNOPKG_PKGNAME}/db ${SYNOPKG_PKGDEST}/db/
        rm -r ${TMP_DIR}/${SYNOPKG_PKGNAME}
 fi

exit 0
}
