#!/bin/sh

{
    if [ "${wizard_enable_aut}" == "false" ]; then
       rm -rf ${SYNOPKG_PKGDEST}/db/accs.db
    else
       sed -i -e "s|@user@|${wizard_username:=admin}|g" ${SYNOPKG_PKGDEST}/db/accs.db
       sed -i -e "s|@password@|${wizard_password:=admin}|g" ${SYNOPKG_PKGDEST}/db/accs.db
    fi
exit 0
}
