#!/bin/sh

TEMP_DIR="${SYNOPKG_TEMP_UPGRADE_FOLDER}/db"

{
    if [ "${wizard_update_data}" == "false" ]; then
        rm -rf ${TEMP_DIR}
        mkdir -p ${TEMP_DIR}
        cp -rfp ${SYNOPKG_PKGDEST}/db/* ${TEMP_DIR}
    else
        exit 0
    fi
exit 0
}
