#!/bin/sh

CONFIG_DIR="${SYNOPKG_PKGDEST}/config"
TEMP_DIR="${SYNOPKG_TEMP_UPGRADE_FOLDER}/config"

{
        rm -rf ${TEMP_DIR}
        mkdir -p ${TEMP_DIR}
        cp -rfp ${CONFIG_DIR}/* ${TEMP_DIR}
    exit 0
}
