#!/bin/sh

    LOG_FILE="${SYNOPKG_PKGDEST}/config/${SYNOPKG_PKGNAME}.log"
    SERVICE_COMMAND="${SYNOPKG_PKGDEST}/bin/${SYNOPKG_PKGNAME}"
    CONFIG_FOLDER="${SYNOPKG_PKGDEST}/config"

start_daemon ()
{
    if [ -r "${CONFIG_FOLDER}/accs.db" ]; then
        echo "Start ${SYNOPKG_PKGNAME} ${SYNOPKG_PKGVER} with authorization" >> ${LOG_FILE}
        ${SERVICE_COMMAND} -p 8091 -d ${CONFIG_FOLDER} -a >> ${LOG_FILE} 2>&1 &
    else
        echo "Start ${SYNOPKG_PKGNAME} ${SYNOPKG_PKGVER} without authorization" >> ${LOG_FILE}
        ${SERVICE_COMMAND} -p 8091 -d ${CONFIG_FOLDER} >> ${LOG_FILE} 2>&1 &
    fi
}

stop_daemon ()
{
        echo "Stop ${SYNOPKG_PKGNAME} ${SYNOPKG_PKGVER}" >> ${LOG_FILE}
	kill `pidof ${SYNOPKG_PKGNAME}` >> ${LOG_FILE} 2>&1
	wait_for_status 1 20 || kill -9 `pidof ${SYNOPKG_PKGNAME}` >> ${LOG_FILE} 2>&1
}

daemon_status ()
{
	status=`ps aux | grep "${SYNOPKG_PKGNAME}" | awk -vpid=$$ '$2 != pid { print $1 }'`
		if [ ! -z "$status" ] && kill -0 `pidof ${SYNOPKG_PKGNAME}` > /dev/null 2>&1; then
			return
		fi
		return 1
}

wait_for_status ()
{
    counter=$2
	while [ ${counter} -gt 0 ]; do
	    daemon_status
	    [ $? -eq $1 ] && return
	    let counter=counter-1
	    sleep 1
	done
	return 1
}

case $1 in
       start)
	    if daemon_status; then
		    echo ${SYNOPKG_PKGNAME} is already running
		    exit 0
		else
		    echo Starting ${SYNOPKG_PKGNAME} ...
		    start_daemon
		    exit $?
		fi
		;;
	stop)
	    if daemon_status; then
		    echo Stopping ${SYNOPKG_PKGNAME} ...
			stop_daemon
			exit $?
	         else
		    echo ${SYNOPKG_PKGNAME} is not running
			exit 0
		fi
		;;
      restart)
	            echo Restarting ${SYNOPKG_PKGNAME} ...
		        stop_daemon
		        start_daemon
		        exit $?
		;;
       status)
	     if daemon_status; then
		     echo ${SYNOPKG_PKGNAME} is running
		         exit 0
		  else
		     echo ${SYNOPKG_PKGNAME} is not running
		         exit 1
		fi
		;;
	 log)
	                 exit 0
	        ;;
	   *)
                     echo "command $1 is not implemented"
                         exit 0
		;;
esac
