#!/bin/sh

    SYNOMODEL=$(cat /proc/sys/kernel/syno_hw_version)
    ARCH=$(uname --machine)
    DSM=$(grep -i "productversion=" "/etc.defaults/VERSION" | cut -d"\"" -f 2)
    DSMVERSION=$(echo "$DSM"-"$(grep -i "buildnumber="    "/etc.defaults/VERSION" | cut -d"\"" -f 2)")

    LOG_FILE="${SYNOPKG_PKGDEST}/config/${SYNOPKG_PKGNAME}.log"
    SERVICE_COMMAND="${SYNOPKG_PKGDEST}/bin/${SYNOPKG_PKGNAME}"
    CONFIG_DIR="${SYNOPKG_PKGDEST}/config"

start_daemon ()
{
    if [ -r "${CONFIG_DIR}/accs.db" ]; then
        echo "" >> ${LOG_FILE}
        echo "Synology $SYNOMODEL ($ARCH) DSM $DSMVERSION" >> ${LOG_FILE}
        echo "Start with authorization" >> ${LOG_FILE}
        ${SERVICE_COMMAND} -d ${CONFIG_DIR} -a -l ${LOG_FILE} &
    else
        echo "" >> ${LOG_FILE}
        echo "Synology $SYNOMODEL ($ARCH) DSM $DSMVERSION" >> ${LOG_FILE}
        echo "Start without authorization" >> ${LOG_FILE}
        ${SERVICE_COMMAND} -d ${CONFIG_DIR} -l ${LOG_FILE} &
    fi
}

stop_daemon ()
{
        echo "Stop" >> ${LOG_FILE}
	kill `pidof ${SYNOPKG_PKGNAME}`
	wait_for_status 1 20 || kill -9 `pidof ${SYNOPKG_PKGNAME}`
}

daemon_status ()
{
	status=`ps aux | grep "${SYNOPKG_PKGNAME}" | awk -vpid=$$ '$2 != pid { print $1 }'`
		if [ ! -z "$status" ] && kill -0 `pidof ${SYNOPKG_PKGNAME}` > /dev/null; then
			return
		fi
		return 1
}

wait_for_status ()
{
    counter=$2
	while [ ${counter} -gt 0 ]; do
	    daemon_status
	    [ $? -eq $1 ] && return
	    let counter=counter-1
	    sleep 1
	done
	return 1
}

case $1 in
       start)
	    if daemon_status; then
		    echo ${SYNOPKG_PKGNAME} is already running
		    exit 0
		else
		    echo Starting ${SYNOPKG_PKGNAME} ...
		    start_daemon
		    exit $?
		fi
		;;
	stop)
	    if daemon_status; then
		    echo Stopping ${SYNOPKG_PKGNAME} ...
			stop_daemon
			exit $?
	         else
		    echo ${SYNOPKG_PKGNAME} is not running
			exit 0
		fi
		;;
      restart)
	            echo Restarting ${SYNOPKG_PKGNAME} ...
		        stop_daemon
		        start_daemon
		        exit $?
		;;
       status)
	     if daemon_status; then
		     echo ${SYNOPKG_PKGNAME} is running
		         exit 0
		  else
		     echo ${SYNOPKG_PKGNAME} is not running
		         exit 1
		fi
		;;
	 log)
	                 exit 0
	        ;;
	   *)
                     echo "command $1 is not implemented"
                         exit 0
		;;
esac
